#!/usr/bin/env bash

set -e

current_branch=$(git rev-parse --abbrev-ref HEAD)
branch=${1:-$current_branch}
remote_base=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
base=${2:-${remote_base}}

echo "Updating pull request ${branch} from ${base}"

git checkout $base
git pull --rebase
git checkout $branch
git rebase $base
git push --force
