#!/usr/bin/env bash

set -e

current_branch=$(git rev-parse --abbrev-ref HEAD)
branch=${1:-$current_branch}
base="master"

echo "Deleting ${branch}"

git checkout $base
git branch -d $branch
git push origin :$branch
