#!/bin/bash
# Modified from https://github.com/joshmedeski/t-smart-tmux-session-manager

if [ "$1" = "-h" ] || [ "$1" == "--help" ]; then
    printf "\n"
    printf "\033[1m  t - the smart tmux session manager\033[0m\n"
    printf "\033[37m  https://github.com/joshmedeski/t-smart-tmux-session-manager\n"
    printf "\n"
    printf "\033[32m  Run interactive mode\n"
    printf "\033[34m      t\n"
    printf "\n"
    printf "\033[32m  Go to session\n"
    printf "\033[34m      t {name}\n"
    printf "\n"
    printf "\033[32m  Open popup (while in tmux)\n"
    printf "\033[34m      <prefix>+T\n"
    printf "\n"
    printf "\033[32m  Show help\n"
    printf "\033[34m      t -h\n"
    printf "\033[34m      t --help\n"
    printf "\n"
elif [ $# -eq 0 ]; then
    FZF_BORDER_LABEL=" t - smart tmux session manager "

    REPOS=~/repos
    DEPTH=3

    if [ "$TMUX" = "" ]; then
        SELECTED_DIRECTORY=$(find $REPOS -type d -depth $DEPTH -maxdepth $DEPTH -name "*" | fzf --reverse --prompt="❯ " --pointer="❯" --marker="❯" --border-label "$FZF_BORDER_LABEL")
        # ZOXIDE_RESULT=$(zoxide query -l | fzf --reverse --border-label "$FZF_BORDER_LABEL")
    else
        SELECTED_DIRECTORY=$(find $REPOS -type d -depth $DEPTH -maxdepth $DEPTH -name "*" | fzf-tmux -p --prompt="❯ " --pointer="❯" --marker="❯" --reverse --border-label "$FZF_BORDER_LABEL")
        # ZOXIDE_RESULT=$(zoxide query -l | fzf-tmux -p --reverse --border-label "$FZF_BORDER_LABEL")
    fi
else
    ZOXIDE_RESULT=$(zoxide query "$1")
fi

if [ "$SELECTED_DIRECTORY" = "" ]; then
# if [ "$ZOXIDE_RESULT" = "" ]; then
    exit # exit silently if no result
fi

#DIRECTORY=$(basename "$ZOXIDE_RESULT")
# DIRECTORY=$(basename "$SELECTED_DIRECTORY")
DIRECTORY="$(basename $(dirname $SELECTED_DIRECTORY))/$(basename $SELECTED_DIRECTORY)"
SESSION_NAME=$(echo "$DIRECTORY" | tr ' ' '_' | tr '.' '_')

SESSION=$(tmux list-sessions | grep -F "$SESSION_NAME" | awk '{print $1}') # find existing session
SESSION=${SESSION//:/} # grab session name

if [ "$TMUX" = "" ]; then # if not currently in tmux
    if [ "$SESSION" = "" ]; then # session does not exist
        # cd "$ZOXIDE_RESULT" || exit 1 # jump to directory
        cd "$SELECTED_DIRECTORY" || exit 1 # jump to directory
        tmux new-session -s "$SESSION_NAME" # create session and attach
    else # session exists
        tmux attach -t "$SESSION" # attach to session
    fi
else # currently in tmux
    if [ "$SESSION" = "" ]; then # session does not exist
        # cd "$ZOXIDE_RESULT" || exit 1 # jump to directory
        cd "$SELECTED_DIRECTORY" || exit 1 # jump to directory
        tmux new-session -d -s "$SESSION_NAME" # create session
        tmux switch-client -t "$SESSION_NAME" # attach to session
    else # session exists
        tmux switch-client -t "$SESSION" # switch to session
    fi
fi
