#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive
apt-get update > /dev/null
apt-get -y install bash git-core tree
su -c "git clone https://github.com/nhhagen/.dotfiles /home/vagrant/.dotfiles" vagrant
su -c "cd /home/vagrant/.dotfiles && bash setup.sh" vagrant

