#!/usr/bin/env bash

set -e

current_branch=$(git rev-parse --abbrev-ref HEAD)
branch=${1:-$current_branch}
master="master"

echo "Updating pull request ${branch} from ${master}"

git checkout $master
git pull --rebase
git checkout $branch
git rebase master
git push --force
